# 使用前请阅读文档：https://bili33.top/posts/MHYY-AutoCheckin-Manual-Gen2/
# 有问题请前往Github开启issue：https://github.com/GamerNoTitle/MHYY/issues

######## 以下为账号配置项，可以多账号，详情请参考文档 ########
accounts:
  # 第一个账号
  - token: #ai=4;ci=1;oi=295552181;ct=v2_5575a9ec65e41cb2e18f3d2bd03a2042e8438604;si=017f2f5845cb6e0ab1223702f1a8f9967cd5c7b914df265ca471c0c1cca61f23;bi=hk4e_cn
    # 关于type：如果你在安卓版的云·原神里面抓的话type应该是2
    # 如果你是网页版抓的，那type应该是16
    # 此处仅供参考，具体以你抓的为准 
    type: 16
    # sysver：如果你是安卓版抓的，这个应该会显示你的安卓版本（鸿蒙不清楚，手上没设备）
    # 如果你是网页版抓的，这个应该是你的系统版本（注：Windows 10和Windows 11都是写的Windows 10）
    sysver: Windows 10
    # deviceid：手机抓的会有这个，抓到什么填什么
    # 如果是网页版抓的，那也是抓到什么填什么
    deviceid: #cf9e141f-2cbc-4dcc-ac22-0505a1417aa4
    # devicename: 手机抓的话就是手机的入网型号，如红米K40为M2012K11AC，红米K50为22021211RC
    # 如果是网页版抓的，填Unknown
    devicename: Unknown
    # devicemodel: 手机抓的填抓出来的手机型号，大概为手机厂商+上面的deviceid，如红米K40为Xiaomi M2012K11AC
    # 如果是网页版抓的，填Unknown
    devicemodel: Unknown
    # appid: 手机抓的固定填1953439974，网页版抓的留空
    appid: 
